---
title: "Training Plots (51-99)"
author: "Charles Liu (304804942)"
date: "10/31/2020"
output: pdf_document
---

# Packages & Set-Up
```{r}
library(readr)
library(ggplot2)
library(dplyr)
library(reshape2)
library(caret)
library(boot)
library(readxl)
library(MLeval)
library(MASS)
library(ISLR)
library(class)
library(mclust)
library(e1071)
library(MLeval)
library(nnet) #for more than 2 response values
setwd(getwd())
training <- read.csv("training.csv", header = TRUE)
test <- read.csv("test.csv", header = TRUE)
sample <- read.csv("sample.csv", header = TRUE)
traintags <- c("NG","OG","TSG")[as.integer(class)+1]
training$classfactor <- factor(traintags, levels=c("NG","OG","TSG"))
```



# Names of Training (51-99)
```{r}
names(training[,51:99])
```



# Training Plots for Variables 51-99
```{r}
plot(training$classfactor, training$Gene_body_hypomethylation_in_cancer)
plot(training$classfactor, training$Gene_body_hypomethylation_in_cancer)
plot(training$classfactor, training$Canyon_genebody_hypermethylation)
plot(training$classfactor, training$intolerant_pLI)
plot(training$classfactor, training$intolerant_pRec)
plot(training$classfactor, training$intolerant_pNull)

plot(training$classfactor, training$Synonymous_Zscore)
plot(training$classfactor, training$Missense_Zscore)
plot(training$classfactor, training$pLOF_Zscore)
plot(training$classfactor, training$dN_to_dS_ratio)
plot(training$classfactor, training$GDI)
plot(training$classfactor, training$RVIS_percentile)

plot(training$classfactor, training$ncRVIS)
plot(training$classfactor, training$ncGERP)
plot(training$classfactor, training$Gene_age)
plot(training$classfactor, training$FamilyMemberCount)
plot(training$classfactor, training$Length_H3K4me3)
plot(training$classfactor, training$Broad_H3K4me3_percentage)

plot(training$classfactor, training$H3K4me3_height)
plot(training$classfactor, training$H3K4me2_width)
plot(training$classfactor, training$Broad_H3K4me2_percentage)
plot(training$classfactor, training$H3K4me2_height)
plot(training$classfactor, training$H3K4me1_width)
plot(training$classfactor, training$Broad_H3K4me1_percentage)

plot(training$classfactor, training$H3K4me1_height)
plot(training$classfactor, training$H3K36me3_width)
plot(training$classfactor, training$Broad_H3K36me3_percentage)
plot(training$classfactor, training$H3K36me3_height)
plot(training$classfactor, training$H3K27ac_width)
plot(training$classfactor, training$Broad_H3K27ac_percentage)

plot(training$classfactor, training$H3K27ac_height)
plot(training$classfactor, training$H3K27me3_width)
plot(training$classfactor, training$Broad_H3K27me3_percentage)
plot(training$classfactor, training$H3K27me3_height)
plot(training$classfactor, training$H3K9me3_width)
plot(training$classfactor, training$Broad_H3K9me3_percentage)

plot(training$classfactor, training$H3K9me3_height)
plot(training$classfactor, training$H3K9ac_width)
plot(training$classfactor, training$Broad_H3K9ac_percentage)
plot(training$classfactor, training$H3K9ac_height)
plot(training$classfactor, training$H3K9me2_width)
plot(training$classfactor, training$Broad_H3K9me2_percentage)

plot(training$classfactor, training$H3K9me2_height)
plot(training$classfactor, training$H3K79me2_width)
plot(training$classfactor, training$Broad_H3K79me2_percentage)
plot(training$classfactor, training$H3K79me2_height)
plot(training$classfactor, training$H4K20me1_width)
plot(training$classfactor, training$Broad_H4K20me1_percentage)

plot(training$classfactor, training$H4K20me1_height)
plot(training$classfactor, training$class)
```