---
title: "Kaggle attempt 3"
author: "Charles Liu (304804942)"
date: "2/28/2020"
output: html_document
---

```{r}
getwd()
library(readr)
library(tidyverse)
library(car)
FifaNoY <- read.csv("C:/Users/cliuk/Documents/UCLA Works/UCLA Winter 2020/Stats 101A/Project/Project Attempts/FifaNoY.csv", stringsAsFactors = FALSE)
FifaTrainNew <- read.csv("C:/Users/cliuk/Documents/UCLA Works/UCLA Winter 2020/Stats 101A/Project/Project Attempts/FifaTrainNew.csv", stringsAsFactors = FALSE)
attach(FifaTrainNew)
```


```{r}
m2 <- lm(log(WageNew) ~ 0 + log(Overall) + log(Positioning) + , data = FifaTrainNew)
summary(m2)
par(mfrow = c(2, 2))
plot(m2)
```


```{r}
leverage <- hatvalues(m2)
nrow(FifaTrainNew) 
leverage_points <- which(leverage >= 2 * (2 + 1)/12745 & abs(rstandard(m2)) >= 2)
outlier_points <- which(leverage >= 2 * mean(leverage) & abs(rstandard(m2)) >= 2)
bad_leverages <- intersect(leverage_points, outlier_points)
```


```{r}
m3 <- lm(log(WageNew) ~ 0 + Overall + Positioning, data = FifaTrainNew[-bad_leverages, ])
summary(m3)
par(mfrow = c(2, 2))
plot(m3)
```



```{r}
new_data <- data.frame(FifaNoY$Overall, FifaNoY$Positioning)
names(new_data) <- c("Overall", "Positioning")
predicts <- predict(m3, new_data) %>% as.data.frame()
predictions <- cbind(FifaNoY$Ob, predicts)
names(predictions) <- c("Ob","WageNew")
predictions$WageNew <- ifelse(is.na(predictions$WageNew), mean(FifaTrainNew$WageNew), predictions$WageNew)
wageNew <- predict(m3, FifaNoY)
ifelse(is.na(wageNew), mean(FifaTrainNew$wageNew), wageNew)
which(is.na(wageNew))
write.csv(predictions, "C:/Users/cliuk/Documents/UCLA Works/UCLA Winter 2020/Stats 101A/Project/Project Attempts/Attempt3.csv", row.names = FALSE)
```

