---
title: "kaggle1"
author: "Cassandra Tai"
date: "January 22, 2020"
output: html_document
---

```{r}
FifaNoY <- read.csv("UCLA Works/UCLA Winter 2020/Stats 101A/Project/Project Attempts/FifaNoY.csv", stringsAsFactors = FALSE)
FifaTrainNew <- read.csv("UCLA Works/UCLA Winter 2020/Stats 101A/Project/Project Attempts/FifaTrainNew.csv", stringsAsFactors = FALSE)
```

```{r}
colnames(FifaNoY)
```
what about first predicting skills
-stamina
-agility 
- ball control 
- position

```{r}
SLR1 <- lm(data = FifaTrainNew, WageNew ~ Club + Stamina + Agility)
summary(SLR1)
```

```{r}
par(mfrow=c(2,2))
plot(SLR1)
```


Factors impacting wages
-club
-
```{r}
SLR.Club <- lm(data = FifaTrainNew, WageNew ~ Club)
summary(SLR.Club)
par(mfrow=c(2,2))
plot(SLR.Club)
```


```{r}
library(dplyr)
new_data = data.frame(FifaNoY$Club)
names(new_data) = "Club"
predicts <- predict(SLR.Club, new_data) %>% as.data.frame()
predictions <- cbind(FifaNoY$Ob, predicts)

names(predictions) <- c("Ob","WageNew")
predictions$WageNew <- ifelse(is.na(predictions$WageNew), mean(FifaTrainNew$WageNew), predictions$WageNew)

```

```{r}
write.csv(predictions, "C:/Users/cassa/Documents/UCLA/Third Year/WINTER 2020/STATS 101A/kaggleOne.csv", row.names = FALSE)
```

