---
title: "Stats 101A Kaggle Try 1"
author: "Melinda Liu"
date: "1/22/2020"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
FifaTrainNew <- read.csv("Project Attempts/FifaTrainNew.csv", stringsAsFactors = FALSE)

model <- lm(WageNew ~ Overall + Club + CM + CF + CB + ST + CAM , data = FifaTrainNew)

summary(lm( WageNew ~ Overall + Club + CM + CF + CB + ST + CAM, data = FifaTrainNew))$adj.r.squared

attributes(summary(model))
summary(model)$coefficients

plot(model)
summary(lm(log(WageNew) ~ 0 + Overall * Club * Composure, data = FifaTrainNew))

summary(powerTransform(cbind(WageNew, Composure)~1, data = FifaTrainNew))

FifaTrainNew$Position2 <- ifelse(FifaTrainNew$Position %in% c("LCB","RB","RCB","CB","LDM","LB","CDM","RDM"), "Defensive",
                          ifelse(FifaTrainNew$Position %in% c("CAM","ST","CF","LS","RS","RAM","LF","RF","LAM"), "Attacking",
                                 ifelse(FifaTrainNew$Position %in% c("LM","CM","LCM","RM","RW","LW","RCM","LWB","RWB"), "Neutral",
                                        ifelse(FifaTrainNew$Position == "GK", "Goalkeeper", FifaTrainNew$Position))))

FifaTrainNew$Position3 <- ifelse(FifaTrainNew$Position %in% c("CB","CDM", "CM", "CAM", "CF", "ST"), "Center",
                          ifelse(FifaTrainNew$Position %in% c("RB","RCB","RS","RAM","RF","RWB","RCM", "RM", "RDM"), "Right",
                                 ifelse(FifaTrainNew$Position %in% c("LM","LCM","RM","RW","LW","RCM","LWB","LS", "LF","LCB", "LAM", "LB", "LDM"), "Left",
                                        ifelse(FifaTrainNew$Position == "GK", "Goalkeeper", FifaTrainNew$Position))) )

FifaTrainNew$Position3[is.na(FifaTrainNew$Position3)] <- "NA"
FifaTrainNew$Position3 <- as.factor(FifaTrainNew$Position3)

model1.1 <- lm(log(WageNew) ~ 0 + I(Overall^2)* Position3, data = FifaTrainNew)
summary(model1.1)
plot(model1.1)

leverages <- hatvalues(model1.1)
# h_ii > 2 * (p+1)/n
leverage_points <- which(leverages > 2 * mean(leverages))
outliers <- which(abs(rstandard(model1.1)) > 4)
bad_leverages <- intersect(leverage_points, outliers)
bad_leverages

model1.2 <- lm(log(WageNew) ~ 0 + I(Overall^2) * Position3  , data = FifaTrainNew[-bad_leverages,], na.action = na.omit)
summary(model1.2)

diagPlot(model1.2)

sum(is.na(FifaNoYTest$Position3))

```


```{r}
FifaNoYTest <- read.csv("~/Downloads/FifaNoY.csv")
#new_predictor <- FifaNoYTest$Potential
#new_wages <- -125235 + 1917 * new_predictor

new_predictors <- data.frame(
  Overall <- FifaNoYTest$Overall,
  Club <- FifaNoYTest$Club,
  #CM <- as.integer(FifaNoYTest$CM),
  CF <- as.factor(as.numeric(FifaNoYTest$CF)),
  CB <- as.numeric(FifaNoYTest$CB),
  ST <- as.numeric(FifaNoYTest$ST),
  CAM <- as.numeric(FifaNoYTest$CAM)
)

FifaNoYTest$Position3 <- ifelse(FifaNoYTest$Position %in% c("CB","CDM", "CM", "CAM", "CF", "ST"), "Center",
                          ifelse(FifaNoYTest$Position %in% c("RB","RCB","RS","RAM","RF","RWB","RCM", "RM", "RDM"), "Right",
                                 ifelse(FifaNoYTest$Position %in% c("LM","LCM","RM","RW","LW","RCM","LWB","LS", "LF","LCB", "LAM", "LB", "LDM"), "Left",
                                        ifelse(FifaNoYTest$Position == "GK", "Goalkeeper", FifaNoYTest$Position))))

predictions <- data.frame(cbind("Ob" = FifaNoYTest$Ob, "WageNew" = exp(predict(model1.2, FifaNoYTest ))))

FifaNoYTest$Position3[is.na(FifaNoYTest$Position3)] <- "NA"
FifaNoYTest$Position3 <- as.factor(FifaNoYTest$Position3)

#predictions <- predict(model1.2, newdata = new_predictors, interval = "prediction")

predictions <- data.frame( "Ob" = (1:5462), "WageNew" = new_wages, row.names = NULL )
predictions

sum(is.na(predictions$WageNew))

write.csv(predictions, file = "KagglePrediction.csv", row.names = FALSE)

predictions <- data.frame( "Ob" = (1:5462), "WageNew" = as.data.frame(predictions)$fit, row.names = NULL )
write.csv(predictions, file = "Melinda_Liu_HW2_Predictions.csv", row.names = FALSE)

as.data.frame(predictions)$fit
```



```{r}
SampleSol <- read.csv("~/Downloads/SampleSol.csv")
head(SampleSol)
```



```{r}

```